import {
  Bath,
  BedDouble,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calendar,
  Car,
  ChartColumn,
  ChevronsUp,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Coins,
  Copy,
  Eye,
  FileSignature,
  FileText,
  Filter,
  Frown,
  Gauge,
  GraduationCap,
  Hammer,
  Handshake,
  Heart,
  Hourglass,
  House,
  Image,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  Lightbulb,
  ListChecks,
  Lock,
  type LucideIcon,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Mountain,
  PenLine,
  Percent,
  Puzzle,
  Rocket,
  Ruler,
  Scale,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Shuffle,
  Smartphone,
  Smile,
  Sparkles,
  SquareTerminal,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  TrainFront,
  Trees,
  TrendingUp,
  Trophy,
  User,
  Users,
  Video,
  Wallet,
  WandSparkles,
  Warehouse,
  Waves,
  Banknote,
} from "lucide-react";
import { Img, staticFile } from "remotion";

// Ключи иконок для полей `icon` в edit.json. Неизвестный ключ → Sparkles.
export const ICONS: Record<string, LucideIcon> = {
  // время, деньги, рост
  time: Clock,
  hourglass: Hourglass,
  calendar: Calendar,
  money: Banknote,
  coins: Coins,
  wallet: Wallet,
  sales: Tag,
  price: Tag,
  growth: TrendingUp,
  chart: ChartColumn,
  levelup: ChevronsUp,
  rocket: Rocket,
  speed: Gauge,
  percent: Percent,
  // оценки
  error: CircleAlert,
  wrong: CircleX,
  right: CircleCheck,
  question: CircleQuestionMark,
  idea: Lightbulb,
  brain: Brain,
  ai: Bot,
  magic: Sparkles,
  wand: WandSparkles,
  prompt: SquareTerminal,
  chat: MessageCircle,
  write: PenLine,
  copy: Copy,
  document: FileText,
  checklist: ListChecks,
  target: Target,
  search: Search,
  filter: Filter,
  settings: Settings,
  puzzle: Puzzle,
  shuffle: Shuffle,
  key: KeyRound,
  lock: Lock,
  eye: Eye,
  person: User,
  clients: Users,
  business: Briefcase,
  learn: GraduationCap,
  book: BookOpen,
  phone: Smartphone,
  laptop: Laptop,
  photo: Image,
  video: Video,
  voice: Mic,
  language: Languages,
  love: Heart,
  happy: Smile,
  sad: Frown,
  star: Star,
  trophy: Trophy,
  send: Send,
  // недвижимость
  home: House,
  house: House,
  apartment: Building2,
  building: Building,
  newbuild: Building2,
  commercial: Store,
  warehouse: Warehouse,
  map: Map,
  location: MapPin,
  area: Ruler,
  rooms: BedDouble,
  bath: Bath,
  parking: Car,
  deal: Handshake,
  contract: FileSignature,
  family: Users,
  school: GraduationCap,
  park: Trees,
  metro: TrainFront,
  bank: Landmark,
  mortgage: Landmark,
  safe: ShieldCheck,
  legal: Scale,
  repair: Hammer,
  sun: Sun,
  view: Mountain,
  water: Waves,
};

export const iconKeys = Object.keys(ICONS);

export const Icon: React.FC<{ name: string; size: number; color: string; stroke?: number }> = ({
  name,
  size,
  color,
  stroke = 1.6,
}) => {
  // file:<png в public/logos> — свой логотип
  if (name.startsWith("file:")) {
    return (
      <Img
        src={staticFile(`logos/${name.slice(5)}`)}
        style={{ width: size, height: size, objectFit: "contain" }}
      />
    );
  }
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp size={size} color={color} strokeWidth={stroke} absoluteStrokeWidth={false} />;
};
